FROM eclipse-temurin:17-jre-alpine

RUN addgroup -S afra7kom && adduser -S afra7kom -G afra7kom

WORKDIR /app

RUN mkdir -p /app/uploads /app/logs /app/config && chown -R afra7kom:afra7kom /app

COPY app.jar app.jar
RUN chown afra7kom:afra7kom app.jar

USER afra7kom

EXPOSE 8080

ENV SPRING_PROFILES_ACTIVE=prod
ENV SERVER_PORT=8080

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS:--Xms512m -Xmx1536m} -jar app.jar"]
